version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msmailer
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3307"

    volumes:
      - ./init:/docker-entrypoint-initdb.d