version: '3.1'

services:

  my_events_db:
    container_name: "my-events-db"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"

    volumes:
      - ./init/init-db.sql:/docker-entrypoint-initdb.d/dump.sql
